version: '2'

services:
  web:
    build: .
    command: bash -c "cd ./nearby && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: nearby_hospital_service
    volumes:
      - .:/nearby_hospital_service
    ports:
      - "8000:8000"